// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OTIS

#ifndef _OTIS_UI_H
#define _OTIS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_splash.h"
#include "ui_homeScreen.h"
#include "ui_authentication.h"
#include "ui_editMaterialScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_png);    // assets/logo.png
LV_IMG_DECLARE(ui_img_small_logo_png);    // assets/small_logo.png
LV_IMG_DECLARE(ui_img_audio_png);    // assets/audio.png
LV_IMG_DECLARE(ui_img_edit_png);    // assets/edit.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
