// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OTIS

#ifndef UI_AUTHENTICATION_H
#define UI_AUTHENTICATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_authentication
extern void ui_authentication_screen_init(void);
extern void ui_authentication_screen_destroy(void);
extern lv_obj_t * ui_authentication;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_closeButton;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_inputContainer;
extern lv_obj_t * ui_passwordInput;
extern lv_obj_t * ui_Keyboard1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

