// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OTIS

#include "ui.h"

lv_obj_t * ui_authentication = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_logo = NULL;
lv_obj_t * ui_closeButton = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_inputContainer = NULL;
lv_obj_t * ui_passwordInput = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
// event funtions

// build funtions

void ui_authentication_screen_init(void)
{
    ui_authentication = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_authentication, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_authentication, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_authentication, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_Container10 = lv_obj_create(ui_authentication);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_height(ui_Container10, 61);
    lv_obj_set_width(ui_Container10, lv_pct(95));
    lv_obj_set_x(ui_Container10, -11);
    lv_obj_set_y(ui_Container10, -1);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_logo = lv_img_create(ui_Container10);
    lv_img_set_src(ui_logo, &ui_img_small_logo_png);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_closeButton = lv_btn_create(ui_Container10);
    lv_obj_set_width(ui_closeButton, 80);
    lv_obj_set_height(ui_closeButton, 30);
    lv_obj_set_align(ui_closeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_closeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_closeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_closeButton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Close");

    ui_inputContainer = lv_obj_create(ui_authentication);
    lv_obj_remove_style_all(ui_inputContainer);
    lv_obj_set_width(ui_inputContainer, 430);
    lv_obj_set_height(ui_inputContainer, 48);
    lv_obj_set_x(ui_inputContainer, -6);
    lv_obj_set_y(ui_inputContainer, -2);
    lv_obj_set_align(ui_inputContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_inputContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_passwordInput = lv_textarea_create(ui_inputContainer);
    lv_obj_set_width(ui_passwordInput, 281);
    lv_obj_set_height(ui_passwordInput, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_passwordInput, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_passwordInput, "Password");
    lv_textarea_set_one_line(ui_passwordInput, true);
    lv_textarea_set_password_mode(ui_passwordInput, true);
    lv_obj_set_style_text_align(ui_passwordInput, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_authentication);
    lv_keyboard_set_mode(ui_Keyboard1, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard1, 431);
    lv_obj_set_height(ui_Keyboard1, 177);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    lv_keyboard_set_textarea(ui_Keyboard1, ui_passwordInput);

}

void ui_authentication_screen_destroy(void)
{
    if(ui_authentication) lv_obj_del(ui_authentication);

    // NULL screen variables
    ui_authentication = NULL;
    ui_Container10 = NULL;
    ui_logo = NULL;
    ui_closeButton = NULL;
    ui_Label4 = NULL;
    ui_inputContainer = NULL;
    ui_passwordInput = NULL;
    ui_Keyboard1 = NULL;

}
