// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OTIS

#include "ui.h"

lv_obj_t * ui_editMaterialScreen = NULL;
lv_obj_t * ui_Editheader = NULL;
lv_obj_t * ui_logo2 = NULL;
lv_obj_t * ui_editCloseButton = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_furnaceDropdownContianer = NULL;
lv_obj_t * ui_furnaceLabel = NULL;
lv_obj_t * ui_marginCt = NULL;
lv_obj_t * ui_furnaceOption = NULL;
lv_obj_t * ui_materialDropdownContianer = NULL;
lv_obj_t * ui_materialLabel = NULL;
lv_obj_t * ui_marginCt1 = NULL;
lv_obj_t * ui_materialOption = NULL;
lv_obj_t * ui_saveButton = NULL;
lv_obj_t * ui_saveButtonLabel = NULL;
// event funtions

// build funtions

void ui_editMaterialScreen_screen_init(void)
{
    ui_editMaterialScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_editMaterialScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_editMaterialScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_editMaterialScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_Editheader = lv_obj_create(ui_editMaterialScreen);
    lv_obj_remove_style_all(ui_Editheader);
    lv_obj_set_height(ui_Editheader, 61);
    lv_obj_set_width(ui_Editheader, lv_pct(95));
    lv_obj_set_x(ui_Editheader, -11);
    lv_obj_set_y(ui_Editheader, -1);
    lv_obj_set_align(ui_Editheader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Editheader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Editheader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Editheader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_logo2 = lv_img_create(ui_Editheader);
    lv_img_set_src(ui_logo2, &ui_img_small_logo_png);
    lv_obj_set_width(ui_logo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_logo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_editCloseButton = lv_btn_create(ui_Editheader);
    lv_obj_set_width(ui_editCloseButton, 80);
    lv_obj_set_height(ui_editCloseButton, 30);
    lv_obj_set_align(ui_editCloseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_editCloseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_editCloseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_editCloseButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Close");

    ui_furnaceDropdownContianer = lv_obj_create(ui_editMaterialScreen);
    lv_obj_remove_style_all(ui_furnaceDropdownContianer);
    lv_obj_set_height(ui_furnaceDropdownContianer, 82);
    lv_obj_set_width(ui_furnaceDropdownContianer, lv_pct(87));
    lv_obj_set_x(ui_furnaceDropdownContianer, -2);
    lv_obj_set_y(ui_furnaceDropdownContianer, -30);
    lv_obj_set_align(ui_furnaceDropdownContianer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_furnaceDropdownContianer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_furnaceDropdownContianer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_furnaceDropdownContianer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_furnaceLabel = lv_label_create(ui_furnaceDropdownContianer);
    lv_obj_set_width(ui_furnaceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_furnaceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_furnaceLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_furnaceLabel, "Furnaces");
    lv_obj_set_style_text_font(ui_furnaceLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_marginCt = lv_obj_create(ui_furnaceDropdownContianer);
    lv_obj_remove_style_all(ui_marginCt);
    lv_obj_set_width(ui_marginCt, 10);
    lv_obj_set_height(ui_marginCt, 10);
    lv_obj_set_align(ui_marginCt, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_marginCt, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_furnaceOption = lv_dropdown_create(ui_furnaceDropdownContianer);
    lv_obj_set_width(ui_furnaceOption, 406);
    lv_obj_set_height(ui_furnaceOption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_furnaceOption, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_furnaceOption, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_materialDropdownContianer = lv_obj_create(ui_editMaterialScreen);
    lv_obj_remove_style_all(ui_materialDropdownContianer);
    lv_obj_set_height(ui_materialDropdownContianer, 82);
    lv_obj_set_width(ui_materialDropdownContianer, lv_pct(87));
    lv_obj_set_x(ui_materialDropdownContianer, -2);
    lv_obj_set_y(ui_materialDropdownContianer, -30);
    lv_obj_set_align(ui_materialDropdownContianer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_materialDropdownContianer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_materialDropdownContianer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_materialDropdownContianer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_materialLabel = lv_label_create(ui_materialDropdownContianer);
    lv_obj_set_width(ui_materialLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_materialLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_materialLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_materialLabel, "Materials");
    lv_obj_set_style_text_font(ui_materialLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_marginCt1 = lv_obj_create(ui_materialDropdownContianer);
    lv_obj_remove_style_all(ui_marginCt1);
    lv_obj_set_width(ui_marginCt1, 10);
    lv_obj_set_height(ui_marginCt1, 10);
    lv_obj_set_align(ui_marginCt1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_marginCt1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_materialOption = lv_dropdown_create(ui_materialDropdownContianer);
    lv_obj_set_width(ui_materialOption, 406);
    lv_obj_set_height(ui_materialOption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_materialOption, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_materialOption, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_saveButton = lv_btn_create(ui_editMaterialScreen);
    lv_obj_set_width(ui_saveButton, 100);
    lv_obj_set_height(ui_saveButton, 50);
    lv_obj_set_x(ui_saveButton, -10);
    lv_obj_set_y(ui_saveButton, 121);
    lv_obj_set_align(ui_saveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_saveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_saveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_saveButtonLabel = lv_label_create(ui_saveButton);
    lv_obj_set_width(ui_saveButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_saveButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_saveButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_saveButtonLabel, "Save");

}

void ui_editMaterialScreen_screen_destroy(void)
{
    if(ui_editMaterialScreen) lv_obj_del(ui_editMaterialScreen);

    // NULL screen variables
    ui_editMaterialScreen = NULL;
    ui_Editheader = NULL;
    ui_logo2 = NULL;
    ui_editCloseButton = NULL;
    ui_Label2 = NULL;
    ui_furnaceDropdownContianer = NULL;
    ui_furnaceLabel = NULL;
    ui_marginCt = NULL;
    ui_furnaceOption = NULL;
    ui_materialDropdownContianer = NULL;
    ui_materialLabel = NULL;
    ui_marginCt1 = NULL;
    ui_materialOption = NULL;
    ui_saveButton = NULL;
    ui_saveButtonLabel = NULL;

}
