// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OTIS

#ifndef UI_EDITMATERIALSCREEN_H
#define UI_EDITMATERIALSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_editMaterialScreen
extern void ui_editMaterialScreen_screen_init(void);
extern void ui_editMaterialScreen_screen_destroy(void);
extern lv_obj_t * ui_editMaterialScreen;
extern lv_obj_t * ui_Editheader;
extern lv_obj_t * ui_logo2;
extern lv_obj_t * ui_editCloseButton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_furnaceDropdownContianer;
extern lv_obj_t * ui_furnaceLabel;
extern lv_obj_t * ui_marginCt;
extern lv_obj_t * ui_furnaceOption;
extern lv_obj_t * ui_materialDropdownContianer;
extern lv_obj_t * ui_materialLabel;
extern lv_obj_t * ui_marginCt1;
extern lv_obj_t * ui_materialOption;
extern lv_obj_t * ui_saveButton;
extern lv_obj_t * ui_saveButtonLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

