// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OTIS

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_homeScreen
extern void ui_homeScreen_screen_init(void);
extern void ui_homeScreen_screen_destroy(void);
extern lv_obj_t * ui_homeScreen;
extern lv_obj_t * ui_header;
extern lv_obj_t * ui_smallLogoContainer;
extern lv_obj_t * ui_smalllogo;
extern lv_obj_t * ui_timestamp;
extern lv_obj_t * ui_timeText;
extern lv_obj_t * ui_networkContainer;
extern lv_obj_t * ui_network;
extern lv_obj_t * ui_below20;
extern lv_obj_t * ui_below40;
extern lv_obj_t * ui_below60;
extern lv_obj_t * ui_below80;
extern lv_obj_t * ui_fullNetwork;
extern lv_obj_t * ui_furnace;
extern lv_obj_t * ui_headerCont;
extern lv_obj_t * ui_furnaceName;
extern lv_obj_t * ui_stats;
extern lv_obj_t * ui_furnaceControl;
extern lv_obj_t * ui_levelPanel;
extern lv_obj_t * ui_levelLabeel;
extern lv_obj_t * ui_levelValue;
extern lv_obj_t * ui_levelUnit;
extern lv_obj_t * ui_margin;
extern lv_obj_t * ui_controls;
extern lv_obj_t * ui_indicators;
extern lv_obj_t * ui_indicatorLabel;
extern lv_obj_t * ui_allIndicators;
extern lv_obj_t * ui_redIndicator;
extern lv_obj_t * ui_greenIndicator;
extern lv_obj_t * ui_yellowIndicator;
extern lv_obj_t * ui_audioIndicator;
extern lv_obj_t * ui_audioImage;
extern lv_obj_t * ui_materialContainer;
extern lv_obj_t * ui_materialOptions;
extern lv_obj_t * ui_marginC;
extern lv_obj_t * ui_materialEdit;
extern lv_obj_t * ui_editIcon;
extern lv_obj_t * ui_navbar;
extern lv_obj_t * ui_prev;
extern lv_obj_t * ui_prevLabelText;
extern lv_obj_t * ui_next;
extern lv_obj_t * ui_nextLabel;
extern lv_obj_t * ui_tag;
extern lv_obj_t * ui_poweredByLabel;
extern lv_obj_t * ui_rada2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

