// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OTIS

#include "ui.h"

lv_obj_t * ui_homeScreen = NULL;
lv_obj_t * ui_header = NULL;
lv_obj_t * ui_smallLogoContainer = NULL;
lv_obj_t * ui_smalllogo = NULL;
lv_obj_t * ui_timestamp = NULL;
lv_obj_t * ui_timeText = NULL;
lv_obj_t * ui_networkContainer = NULL;
lv_obj_t * ui_network = NULL;
lv_obj_t * ui_below20 = NULL;
lv_obj_t * ui_below40 = NULL;
lv_obj_t * ui_below60 = NULL;
lv_obj_t * ui_below80 = NULL;
lv_obj_t * ui_fullNetwork = NULL;
lv_obj_t * ui_furnace = NULL;
lv_obj_t * ui_headerCont = NULL;
lv_obj_t * ui_furnaceName = NULL;
lv_obj_t * ui_stats = NULL;
lv_obj_t * ui_furnaceControl = NULL;
lv_obj_t * ui_levelPanel = NULL;
lv_obj_t * ui_levelLabeel = NULL;
lv_obj_t * ui_levelValue = NULL;
lv_obj_t * ui_levelUnit = NULL;
lv_obj_t * ui_margin = NULL;
lv_obj_t * ui_controls = NULL;
lv_obj_t * ui_indicators = NULL;
lv_obj_t * ui_indicatorLabel = NULL;
lv_obj_t * ui_allIndicators = NULL;
lv_obj_t * ui_redIndicator = NULL;
lv_obj_t * ui_greenIndicator = NULL;
lv_obj_t * ui_yellowIndicator = NULL;
lv_obj_t * ui_audioIndicator = NULL;
lv_obj_t * ui_audioImage = NULL;
lv_obj_t * ui_materialContainer = NULL;
lv_obj_t * ui_materialOptions = NULL;
lv_obj_t * ui_marginC = NULL;
lv_obj_t * ui_materialEdit = NULL;
lv_obj_t * ui_editIcon = NULL;
lv_obj_t * ui_navbar = NULL;
lv_obj_t * ui_prev = NULL;
lv_obj_t * ui_prevLabelText = NULL;
lv_obj_t * ui_next = NULL;
lv_obj_t * ui_nextLabel = NULL;
lv_obj_t * ui_tag = NULL;
lv_obj_t * ui_poweredByLabel = NULL;
lv_obj_t * ui_rada2 = NULL;
// event funtions

// build funtions

void ui_homeScreen_screen_init(void)
{
    ui_homeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_homeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_homeScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_homeScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_header = lv_obj_create(ui_homeScreen);
    lv_obj_remove_style_all(ui_header);
    lv_obj_set_height(ui_header, 49);
    lv_obj_set_width(ui_header, lv_pct(100));
    lv_obj_set_x(ui_header, -18);
    lv_obj_set_y(ui_header, -33);
    lv_obj_set_align(ui_header, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_header, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_header, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_header, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_smallLogoContainer = lv_obj_create(ui_header);
    lv_obj_remove_style_all(ui_smallLogoContainer);
    lv_obj_set_width(ui_smallLogoContainer, lv_pct(19));
    lv_obj_set_height(ui_smallLogoContainer, lv_pct(100));
    lv_obj_set_align(ui_smallLogoContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_smallLogoContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_smallLogoContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_smallLogoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_smalllogo = lv_img_create(ui_smallLogoContainer);
    lv_img_set_src(ui_smalllogo, &ui_img_small_logo_png);
    lv_obj_set_width(ui_smalllogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_smalllogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_smalllogo, -39);
    lv_obj_set_y(ui_smalllogo, -130);
    lv_obj_set_align(ui_smalllogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_smalllogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_smalllogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timestamp = lv_obj_create(ui_header);
    lv_obj_remove_style_all(ui_timestamp);
    lv_obj_set_width(ui_timestamp, lv_pct(50));
    lv_obj_set_height(ui_timestamp, lv_pct(100));
    lv_obj_set_align(ui_timestamp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_timestamp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_timeText = lv_label_create(ui_timestamp);
    lv_obj_set_width(ui_timeText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timeText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeText, "2025/08/08 12:22:33");
    lv_obj_set_style_text_decor(ui_timeText, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_timeText, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_networkContainer = lv_obj_create(ui_header);
    lv_obj_remove_style_all(ui_networkContainer);
    lv_obj_set_height(ui_networkContainer, 50);
    lv_obj_set_width(ui_networkContainer, lv_pct(19));
    lv_obj_set_align(ui_networkContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_networkContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_networkContainer, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_networkContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_network = lv_obj_create(ui_networkContainer);
    lv_obj_remove_style_all(ui_network);
    lv_obj_set_width(ui_network, 44);
    lv_obj_set_height(ui_network, 31);
    lv_obj_set_x(ui_network, -22);
    lv_obj_set_y(ui_network, 2);
    lv_obj_set_align(ui_network, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_network, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_network, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_END);
    lv_obj_clear_flag(ui_network, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(ui_network, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_network, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_network, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_network, 20, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_below20 = lv_obj_create(ui_network);
    lv_obj_set_width(ui_below20, 8);
    lv_obj_set_height(ui_below20, lv_pct(20));
    lv_obj_set_align(ui_below20, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_below20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_below20, lv_color_hex(0x570101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_below20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_below40 = lv_obj_create(ui_network);
    lv_obj_set_width(ui_below40, 8);
    lv_obj_set_height(ui_below40, lv_pct(40));
    lv_obj_set_align(ui_below40, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_below40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_below40, lv_color_hex(0x570101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_below40, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_below60 = lv_obj_create(ui_network);
    lv_obj_set_width(ui_below60, 8);
    lv_obj_set_height(ui_below60, lv_pct(60));
    lv_obj_set_align(ui_below60, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_below60, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_below60, lv_color_hex(0x570101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_below60, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_below80 = lv_obj_create(ui_network);
    lv_obj_set_width(ui_below80, 8);
    lv_obj_set_height(ui_below80, lv_pct(80));
    lv_obj_set_align(ui_below80, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_below80, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_below80, lv_color_hex(0x570101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_below80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_fullNetwork = lv_obj_create(ui_network);
    lv_obj_set_width(ui_fullNetwork, 8);
    lv_obj_set_height(ui_fullNetwork, lv_pct(100));
    lv_obj_set_align(ui_fullNetwork, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_fullNetwork, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_fullNetwork, lv_color_hex(0x570101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_fullNetwork, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_furnace = lv_obj_create(ui_homeScreen);
    lv_obj_remove_style_all(ui_furnace);
    lv_obj_set_width(ui_furnace, lv_pct(100));
    lv_obj_set_height(ui_furnace, lv_pct(80));
    lv_obj_set_x(ui_furnace, -10);
    lv_obj_set_y(ui_furnace, 32);
    lv_obj_set_align(ui_furnace, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_furnace, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_furnace, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_furnace, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_headerCont = lv_obj_create(ui_furnace);
    lv_obj_remove_style_all(ui_headerCont);
    lv_obj_set_height(ui_headerCont, 24);
    lv_obj_set_width(ui_headerCont, lv_pct(100));
    lv_obj_set_align(ui_headerCont, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_headerCont, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_headerCont, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_headerCont, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_furnaceName = lv_label_create(ui_headerCont);
    lv_obj_set_width(ui_furnaceName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_furnaceName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_furnaceName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_furnaceName, "Furnace Name");
    lv_obj_set_style_text_font(ui_furnaceName, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stats = lv_label_create(ui_headerCont);
    lv_obj_set_width(ui_stats, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_stats, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_stats, LV_ALIGN_CENTER);
    lv_label_set_text(ui_stats, "(-/-)");

    ui_furnaceControl = lv_obj_create(ui_furnace);
    lv_obj_remove_style_all(ui_furnaceControl);
    lv_obj_set_height(ui_furnaceControl, 171);
    lv_obj_set_width(ui_furnaceControl, lv_pct(92));
    lv_obj_set_align(ui_furnaceControl, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_furnaceControl, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_furnaceControl, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_furnaceControl, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_levelPanel = lv_obj_create(ui_furnaceControl);
    lv_obj_set_width(ui_levelPanel, lv_pct(46));
    lv_obj_set_height(ui_levelPanel, lv_pct(80));
    lv_obj_set_align(ui_levelPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_levelPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_levelPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_levelPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_levelLabeel = lv_label_create(ui_levelPanel);
    lv_obj_set_width(ui_levelLabeel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_levelLabeel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_levelLabeel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_levelLabeel, "Level");
    lv_obj_set_style_text_font(ui_levelLabeel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_levelValue = lv_label_create(ui_levelPanel);
    lv_obj_set_width(ui_levelValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_levelValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_levelValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_levelValue, "1228");
    lv_obj_set_style_text_font(ui_levelValue, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_levelUnit = lv_label_create(ui_levelPanel);
    lv_obj_set_width(ui_levelUnit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_levelUnit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_levelUnit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_levelUnit, "mm");

    ui_margin = lv_obj_create(ui_furnaceControl);
    lv_obj_remove_style_all(ui_margin);
    lv_obj_set_width(ui_margin, 10);
    lv_obj_set_height(ui_margin, 50);
    lv_obj_set_align(ui_margin, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_margin, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_controls = lv_obj_create(ui_furnaceControl);
    lv_obj_set_width(ui_controls, lv_pct(47));
    lv_obj_set_height(ui_controls, lv_pct(80));
    lv_obj_set_align(ui_controls, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_controls, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_controls, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_controls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_indicators = lv_obj_create(ui_controls);
    lv_obj_remove_style_all(ui_indicators);
    lv_obj_set_width(ui_indicators, lv_pct(115));
    lv_obj_set_height(ui_indicators, lv_pct(60));
    lv_obj_set_align(ui_indicators, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_indicators, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_indicators, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_indicators, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_indicatorLabel = lv_label_create(ui_indicators);
    lv_obj_set_width(ui_indicatorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_indicatorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_indicatorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_indicatorLabel, "Indicators");
    lv_obj_set_style_text_font(ui_indicatorLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_allIndicators = lv_obj_create(ui_indicators);
    lv_obj_remove_style_all(ui_allIndicators);
    lv_obj_set_height(ui_allIndicators, 50);
    lv_obj_set_width(ui_allIndicators, lv_pct(100));
    lv_obj_set_align(ui_allIndicators, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_allIndicators, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_allIndicators, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_allIndicators, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_redIndicator = lv_obj_create(ui_allIndicators);
    lv_obj_set_width(ui_redIndicator, 30);
    lv_obj_set_height(ui_redIndicator, 30);
    lv_obj_set_align(ui_redIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_redIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_redIndicator, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_redIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_greenIndicator = lv_obj_create(ui_allIndicators);
    lv_obj_set_width(ui_greenIndicator, 30);
    lv_obj_set_height(ui_greenIndicator, 30);
    lv_obj_set_align(ui_greenIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_greenIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_greenIndicator, lv_color_hex(0xFF00FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_greenIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_yellowIndicator = lv_obj_create(ui_allIndicators);
    lv_obj_set_width(ui_yellowIndicator, 30);
    lv_obj_set_height(ui_yellowIndicator, 30);
    lv_obj_set_align(ui_yellowIndicator, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_yellowIndicator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_yellowIndicator, lv_color_hex(0x005AFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_yellowIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_audioIndicator = lv_obj_create(ui_allIndicators);
    lv_obj_remove_style_all(ui_audioIndicator);
    lv_obj_set_width(ui_audioIndicator, 40);
    lv_obj_set_height(ui_audioIndicator, 40);
    lv_obj_set_align(ui_audioIndicator, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_audioIndicator, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_audioIndicator, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_audioIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_audioImage = lv_img_create(ui_audioIndicator);
    lv_img_set_src(ui_audioImage, &ui_img_audio_png);
    lv_obj_set_width(ui_audioImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_audioImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_audioImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_audioImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_audioImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_materialContainer = lv_obj_create(ui_controls);
    lv_obj_remove_style_all(ui_materialContainer);
    lv_obj_set_height(ui_materialContainer, 50);
    lv_obj_set_width(ui_materialContainer, lv_pct(116));
    lv_obj_set_x(ui_materialContainer, 12);
    lv_obj_set_y(ui_materialContainer, 1);
    lv_obj_set_align(ui_materialContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_materialContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_materialContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_materialContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_materialOptions = lv_dropdown_create(ui_materialContainer);
    lv_obj_set_width(ui_materialOptions, 150);
    lv_obj_set_height(ui_materialOptions, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_materialOptions, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_materialOptions, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_marginC = lv_obj_create(ui_materialContainer);
    lv_obj_remove_style_all(ui_marginC);
    lv_obj_set_width(ui_marginC, 4);
    lv_obj_set_height(ui_marginC, 35);
    lv_obj_set_align(ui_marginC, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_marginC, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_materialEdit = lv_obj_create(ui_materialContainer);
    lv_obj_set_width(ui_materialEdit, 40);
    lv_obj_set_height(ui_materialEdit, 40);
    lv_obj_set_align(ui_materialEdit, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_materialEdit, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_materialEdit, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_materialEdit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_editIcon = lv_img_create(ui_materialEdit);
    lv_img_set_src(ui_editIcon, &ui_img_edit_png);
    lv_obj_set_width(ui_editIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_editIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_editIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_editIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_editIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navbar = lv_obj_create(ui_furnace);
    lv_obj_remove_style_all(ui_navbar);
    lv_obj_set_height(ui_navbar, 35);
    lv_obj_set_width(ui_navbar, lv_pct(85));
    lv_obj_set_align(ui_navbar, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_navbar, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_navbar, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_navbar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_prev = lv_btn_create(ui_navbar);
    lv_obj_set_width(ui_prev, 100);
    lv_obj_set_height(ui_prev, 30);
    lv_obj_set_align(ui_prev, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_prev, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_prev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_prevLabelText = lv_label_create(ui_prev);
    lv_obj_set_width(ui_prevLabelText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_prevLabelText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_prevLabelText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_prevLabelText, "Previous");

    ui_next = lv_btn_create(ui_navbar);
    lv_obj_set_width(ui_next, 100);
    lv_obj_set_height(ui_next, 30);
    lv_obj_set_align(ui_next, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_next, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_next, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_nextLabel = lv_label_create(ui_next);
    lv_obj_set_width(ui_nextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_nextLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nextLabel, "Next");

    ui_tag = lv_obj_create(ui_furnace);
    lv_obj_remove_style_all(ui_tag);
    lv_obj_set_width(ui_tag, 222);
    lv_obj_set_height(ui_tag, 20);
    lv_obj_set_align(ui_tag, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tag, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_tag, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tag, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_poweredByLabel = lv_label_create(ui_tag);
    lv_obj_set_width(ui_poweredByLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_poweredByLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_poweredByLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_poweredByLabel, "Powered By");

    ui_rada2 = lv_label_create(ui_tag);
    lv_obj_set_width(ui_rada2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rada2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rada2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rada2, " RADA");
    lv_obj_set_style_text_color(ui_rada2, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rada2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rada2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_homeScreen_screen_destroy(void)
{
    if(ui_homeScreen) lv_obj_del(ui_homeScreen);

    // NULL screen variables
    ui_homeScreen = NULL;
    ui_header = NULL;
    ui_smallLogoContainer = NULL;
    ui_smalllogo = NULL;
    ui_timestamp = NULL;
    ui_timeText = NULL;
    ui_networkContainer = NULL;
    ui_network = NULL;
    ui_below20 = NULL;
    ui_below40 = NULL;
    ui_below60 = NULL;
    ui_below80 = NULL;
    ui_fullNetwork = NULL;
    ui_furnace = NULL;
    ui_headerCont = NULL;
    ui_furnaceName = NULL;
    ui_stats = NULL;
    ui_furnaceControl = NULL;
    ui_levelPanel = NULL;
    ui_levelLabeel = NULL;
    ui_levelValue = NULL;
    ui_levelUnit = NULL;
    ui_margin = NULL;
    ui_controls = NULL;
    ui_indicators = NULL;
    ui_indicatorLabel = NULL;
    ui_allIndicators = NULL;
    ui_redIndicator = NULL;
    ui_greenIndicator = NULL;
    ui_yellowIndicator = NULL;
    ui_audioIndicator = NULL;
    ui_audioImage = NULL;
    ui_materialContainer = NULL;
    ui_materialOptions = NULL;
    ui_marginC = NULL;
    ui_materialEdit = NULL;
    ui_editIcon = NULL;
    ui_navbar = NULL;
    ui_prev = NULL;
    ui_prevLabelText = NULL;
    ui_next = NULL;
    ui_nextLabel = NULL;
    ui_tag = NULL;
    ui_poweredByLabel = NULL;
    ui_rada2 = NULL;

}
