// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OTIS

#include "ui.h"

lv_obj_t * ui_splash = NULL;
lv_obj_t * ui_splashLogoContainer = NULL;
lv_obj_t * ui_cmrlogo = NULL;
lv_obj_t * ui_slider = NULL;
lv_obj_t * ui_poweredBy = NULL;
lv_obj_t * ui_t11 = NULL;
lv_obj_t * ui_rada = NULL;
// event funtions

// build funtions

void ui_splash_screen_init(void)
{
    ui_splash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_splash, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_splash, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_splashLogoContainer = lv_obj_create(ui_splash);
    lv_obj_remove_style_all(ui_splashLogoContainer);
    lv_obj_set_width(ui_splashLogoContainer, 357);
    lv_obj_set_height(ui_splashLogoContainer, 157);
    lv_obj_set_x(ui_splashLogoContainer, -119);
    lv_obj_set_y(ui_splashLogoContainer, -132);
    lv_obj_set_align(ui_splashLogoContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_splashLogoContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_splashLogoContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_splashLogoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cmrlogo = lv_img_create(ui_splashLogoContainer);
    lv_img_set_src(ui_cmrlogo, &ui_img_logo_png);
    lv_obj_set_width(ui_cmrlogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cmrlogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cmrlogo, 71);
    lv_obj_set_y(ui_cmrlogo, -18);
    lv_obj_set_align(ui_cmrlogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cmrlogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cmrlogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_slider = lv_slider_create(ui_splash);
    lv_slider_set_value(ui_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_slider, 393);
    lv_obj_set_height(ui_slider, 10);
    lv_obj_set_x(ui_slider, -11);
    lv_obj_set_y(ui_slider, 61);
    lv_obj_set_align(ui_slider, LV_ALIGN_CENTER);

    ui_poweredBy = lv_obj_create(ui_splash);
    lv_obj_remove_style_all(ui_poweredBy);
    lv_obj_set_width(ui_poweredBy, 256);
    lv_obj_set_height(ui_poweredBy, 50);
    lv_obj_set_x(ui_poweredBy, -8);
    lv_obj_set_y(ui_poweredBy, 75);
    lv_obj_set_align(ui_poweredBy, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_poweredBy, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_poweredBy, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_poweredBy, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_t11 = lv_label_create(ui_poweredBy);
    lv_obj_set_width(ui_t11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_t11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_t11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_t11, "Powered by ");

    ui_rada = lv_label_create(ui_poweredBy);
    lv_obj_set_width(ui_rada, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rada, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rada, LV_ALIGN_CENTER);
    lv_label_set_text(ui_rada, "RADA");
    lv_obj_set_style_text_color(ui_rada, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rada, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rada, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_splash_screen_destroy(void)
{
    if(ui_splash) lv_obj_del(ui_splash);

    // NULL screen variables
    ui_splash = NULL;
    ui_splashLogoContainer = NULL;
    ui_cmrlogo = NULL;
    ui_slider = NULL;
    ui_poweredBy = NULL;
    ui_t11 = NULL;
    ui_rada = NULL;

}
