// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: OTIS

#ifndef UI_SPLASH_H
#define UI_SPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_splash
extern void ui_splash_screen_init(void);
extern void ui_splash_screen_destroy(void);
extern lv_obj_t * ui_splash;
extern lv_obj_t * ui_splashLogoContainer;
extern lv_obj_t * ui_cmrlogo;
extern lv_obj_t * ui_slider;
extern lv_obj_t * ui_poweredBy;
extern lv_obj_t * ui_t11;
extern lv_obj_t * ui_rada;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

